name: All Detections To Elastic

on:
  workflow_dispatch:

jobs:
  elastic-detections-all:
    runs-on: ubuntu-latest
    env:
      ELASTIC_KEY: ${{ secrets.ELASTIC_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
      - run: pip install requests
      - run: python development/toml_to_json.py
