name: TOML/MITRE Validation

on:
  push:
    path:
      - 'detections/**.toml'
      - '!**.yml'
  workflow_dispatch:

jobs:
  toml-validation:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11.4'
      - run: pip install requests
      - run: python development/validation.py
      - run: python development/mitre.py
